### ISSUE TITLE
Return seminar_type on route "GET /methods" and "GET /methods/{:id}"

### ISSUE THREAD

**Issue by mheumann** [MethodenDB-YFU/backend#46]
In my opinion it's useful to see the seminar type on the method overview page, but currently I can't receive the information from the api when calling for the method(s).

**Comment by mheumann** [comment]
Oh wait. we have an n:m connection between method and seminar

**Comment by alexmsenger** [comment]
Hmm ... two suggestions: 

1. Either I'll return `seminar_type` instead of `seminar_goal` since it has `seminar_goal` nested.
2. Alternatively I could put a filter parameter in the url `GET /methods/{:id}?seminarType=foobar` 

The latter would possibly reduce the payload but would introduce some sort of context. (I'm either reading / editing VBTs or NBTs) Of course they aren't mutually exclusive.

**Comment by mheumann** [comment]
The latter isn't helpful regarding the fact that I show all methods and not just those belonging to one seminar type. So in my opinion only the first will work allthough it makes the request more expansive.

**Comment by alexmsenger** [comment]
Alright. I'll figure out a way to add the `seminar_type` to the payload at the root without nesting the `seminar_goal`s in it. (Since it would return all `seminar_goal`s associated with the `seminar_type` and not the ones associated with the `method` anyways.)
